[graph]
targets = [
    # Flathub builds these targets so that's what we care aout
    { triple = 'x86_64-unknown-linux-gnu' },
    { triple = 'aarch64-unknown-linux-gnu' },
]

[advisories]
version = 2
ignore = [
    "RUSTSEC-2025-0057", # We don't care that fxhash is no longer maintained
]

[licenses]
version = 2
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "ISC",
    "EUPL-1.2",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = ["https://codeberg.org/swsnr/gnome-app-utils.rs.git"]
