
# cargo-vet audits file

[[audits.proc-macro-crate]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.2.1 -> 3.2.0"

[[audits.ryu]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.5 -> 1.0.19"

[[audits.serde_json]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.138 -> 1.0.139"
notes = "Only documentation changes and dependency updates."

[[audits.strum]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.26.3 -> 0.27.1"

[[audits.strum_macros]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.26.4 -> 0.27.1"

[[trusted.cairo-rs]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-07-08"
end = "2026-02-12"

[[trusted.cairo-sys-rs]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-10-16"
end = "2026-02-12"

[[trusted.gdk-pixbuf]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.gdk-pixbuf-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.gdk4]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.gdk4-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-02-12"

[[trusted.gio]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-08-28"
end = "2026-02-12"

[[trusted.gio-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-09-16"
end = "2026-02-12"

[[trusted.glib]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-02-14"
end = "2026-02-12"

[[trusted.glib-macros]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-07-08"
end = "2026-02-12"

[[trusted.glib-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-09-16"
end = "2026-02-12"

[[trusted.gobject-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.graphene-rs]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-02-12"

[[trusted.graphene-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-02-12"

[[trusted.gsk4]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.gsk4-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-02-12"

[[trusted.gtk4]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.gtk4-macros]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-02-12"

[[trusted.gtk4-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-02-12"

[[trusted.hashbrown]]
criteria = "safe-to-run"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-04-02"
end = "2026-02-12"

[[trusted.libadwaita]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-06-23"
end = "2026-02-12"

[[trusted.libadwaita-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-06-23"
end = "2026-02-12"

[[trusted.libc]]
criteria = "safe-to-run"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2020-03-17"
end = "2026-02-12"

[[trusted.memchr]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2026-02-12"

[[trusted.pango]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-08-11"
end = "2026-02-12"

[[trusted.pango-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.serde_spanned]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2023-01-20"
end = "2026-02-12"

[[trusted.slab]]
criteria = "safe-to-run"
user-id = 6741 # Alice Ryhl (Darksonn)
start = "2021-10-13"
end = "2026-02-12"

[[trusted.soup3]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2022-10-10"
end = "2026-02-22"

[[trusted.soup3-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2022-10-10"
end = "2026-02-22"

[[trusted.syn]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-02-12"

[[trusted.target-lexicon]]
criteria = "safe-to-run"
user-id = 696 # Nick Fitzgerald (fitzgen)
start = "2024-07-30"
end = "2026-02-12"

[[trusted.toml]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2022-12-14"
end = "2026-02-12"

[[trusted.toml_edit]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2021-09-13"
end = "2026-02-12"

[[trusted.winnow]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2023-02-22"
end = "2026-02-12"
