
# cargo-vet audits file

[[audits.async-channel]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "2.3.1 -> 2.5.0"

[[audits.autocfg]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.4.0 -> 1.5.0"

[[audits.bitflags]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "2.9.1 -> 2.9.4"

[[audits.cfg-expr]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.20.1 -> 0.20.2"

[[audits.cfg-expr]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.20.2 -> 0.20.3"

[[audits.cfg-if]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.0 -> 1.0.1"

[[audits.cfg-if]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "1.0.1 -> 1.0.3"

[[audits.concurrent-queue]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "2.1.0 -> 2.5.0"

[[audits.derive_more]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.99.17 -> 0.99.19"

[[audits.derive_more]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.99.19 -> 0.99.20"

[[audits.dtoa-short]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.3.3 -> 0.3.5"

[[audits.ego-tree]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
version = "0.10.0"

[[audits.event-listener]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "5.0.0 -> 5.3.1"

[[audits.event-listener]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "5.4.0 -> 5.4.1"

[[audits.form_urlencoded]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "1.2.1 -> 1.2.2"

[[audits.formatx]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
version = "0.2.4"

[[audits.futf]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
version = "0.1.5"
notes = """
Heavily relies on unsafe, prob. for performance.  unsafe decode looks good, but
didn't audit the other unsafe code in detail.
"""

[[audits.hashbrown]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.15.4 -> 0.15.5"

[[audits.indexmap]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "2.9.0 -> 2.10.0"

[[audits.litemap]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.7.4 -> 0.7.5"

[[audits.log]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.4.27 -> 0.4.28"

[[audits.mac]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
version = "0.1.1"
notes = "Just a few trivial macros, no unsafe code, looks very safe to use."

[[audits.pkg-config]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.3.31 -> 0.3.32"

[[audits.potential_utf]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.1.2 -> 0.1.3"

[[audits.proc-macro-crate]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.2.1 -> 3.2.0"

[[audits.proc-macro-crate]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "3.2.0 -> 3.3.0"

[[audits.proc-macro-crate]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "3.3.0 -> 3.4.0"

[[audits.proc-macro2]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.97 -> 1.0.101"

[[audits.redox_syscall]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.5.12 -> 0.5.13"

[[audits.redox_syscall]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.5.17 -> 0.5.18"

[[audits.ryu]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.5 -> 1.0.19"

[[audits.ryu]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "1.0.19 -> 1.0.20"
notes = "No code changes"

[[audits.scraper]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
version = "0.23.1"

[[audits.serde]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "1.0.227 -> 1.0.228"

[[audits.serde_core]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "1.0.227 -> 1.0.228"

[[audits.serde_derive]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "1.0.227 -> 1.0.228"

[[audits.serde_derive]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "1.0.227 -> 1.0.228"

[[audits.serde_json]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.0.138 -> 1.0.139"
notes = "Only documentation changes and dependency updates."

[[audits.serde_json]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "1.0.142 -> 1.0.143"

[[audits.serde_json]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "1.0.142 -> 1.0.143"

[[audits.servo_arc]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.4.0 -> 0.4.1"
notes = "No actual code changes in this change."

[[audits.siphasher]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
version = "1.0.1"

[[audits.smallvec]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.14.0 -> 1.15.0"

[[audits.smallvec]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.15.0 -> 1.15.1"

[[audits.stable_deref_trait]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.2.0 -> 1.2.1"

[[audits.strum]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.26.3 -> 0.27.1"

[[audits.strum_macros]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.26.4 -> 0.27.1"

[[audits.system-deps]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "7.0.5 -> 7.0.6"
notes = "No real code changes"

[[audits.target-lexicon]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.12.16 -> 0.13.2"

[[audits.utf-8]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
version = "0.7.6"
notes = "Trace amounts of unsafe, didn't audit decoding logic."

[[audits.windows-link]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.2.0 -> 0.2.1"

[[audits.zerofrom]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.1.5 -> 0.1.6"

[[audits.zerofrom-derive]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.1.5 -> 0.1.6"

[[audits.zerovec]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.11.3 -> 0.11.4"

[[trusted.cairo-rs]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-07-08"
end = "2026-02-12"

[[trusted.cairo-sys-rs]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-10-16"
end = "2026-02-12"

[[trusted.concurrent-queue]]
criteria = "safe-to-run"
user-id = 33035 # Taiki Endo (taiki-e)
start = "2022-07-17"
end = "2026-04-25"

[[trusted.dtoa]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2026-04-10"

[[trusted.event-listener]]
criteria = "safe-to-run"
user-id = 6423 # Zeeshan Ali Khan (zeenix)
start = "2024-02-05"
end = "2026-04-25"

[[trusted.event-listener-strategy]]
criteria = "safe-to-run"
user-id = 33035 # Taiki Endo (taiki-e)
start = "2025-03-27"
end = "2026-04-25"

[[trusted.gdk-pixbuf]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.gdk-pixbuf-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.gdk4]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.gdk4]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gdk4-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-02-12"

[[trusted.gdk4-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gdk4-wayland]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-03-06"

[[trusted.gdk4-wayland]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gdk4-wayland-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-03-06"

[[trusted.gdk4-wayland-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gdk4-x11]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-03-07"

[[trusted.gdk4-x11]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gdk4-x11-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-03-07"

[[trusted.gdk4-x11-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gio]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-08-28"
end = "2026-02-12"

[[trusted.gio-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-09-16"
end = "2026-02-12"

[[trusted.glib]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-02-14"
end = "2026-02-12"

[[trusted.glib-macros]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-07-08"
end = "2026-02-12"

[[trusted.glib-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-09-16"
end = "2026-02-12"

[[trusted.gobject-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.graphene-rs]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-02-12"

[[trusted.graphene-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-02-12"

[[trusted.gsk4]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.gsk4]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gsk4-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-02-12"

[[trusted.gsk4-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gtk4]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.gtk4]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gtk4-macros]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-02-12"

[[trusted.gtk4-macros]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.gtk4-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2021-04-04"
end = "2026-02-12"

[[trusted.gtk4-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-07-12"
end = "2026-07-16"

[[trusted.hashbrown]]
criteria = "safe-to-run"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-04-02"
end = "2026-02-12"

[[trusted.html5ever]]
criteria = "safe-to-run"
user-id = 2396 # Josh Matthews (jdm)
start = "2019-04-27"
end = "2026-04-10"
notes = "Respectable whatwg & servo person"

[[trusted.jiff]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2024-02-17"
end = "2026-04-24"

[[trusted.jiff-static]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2025-03-06"
end = "2026-05-16"

[[trusted.libadwaita]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-06-23"
end = "2026-02-12"

[[trusted.libadwaita]]
criteria = "safe-to-run"
user-id = 111887 # Maximiliano (A6GibKm)
start = "2025-03-19"
end = "2026-07-16"
notes = "Maximiliano is a well-known Rust person in the Gnome world"

[[trusted.libadwaita-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2021-06-23"
end = "2026-02-12"

[[trusted.libadwaita-sys]]
criteria = "safe-to-run"
user-id = 111887 # Maximiliano (A6GibKm)
start = "2025-03-19"
end = "2026-07-16"
notes = "Maximiliano is a well-known Rust person in the Gnome world"

[[trusted.libc]]
criteria = "safe-to-run"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2020-03-17"
end = "2026-02-12"

[[trusted.libc]]
criteria = "safe-to-run"
user-id = 55123 # rust-lang-owner
start = "2024-08-15"
end = "2026-03-08"

[[trusted.lock_api]]
criteria = "safe-to-run"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2026-04-10"

[[trusted.markup5ever]]
criteria = "safe-to-run"
user-id = 2396 # Josh Matthews (jdm)
start = "2019-04-27"
end = "2026-04-10"
notes = "Respectable whatwg & servo person"

[[trusted.match_token]]
criteria = "safe-to-run"
user-id = 2396 # Josh Matthews (jdm)
start = "2025-02-04"
end = "2026-04-10"
notes = "Respectable whatwg & servo person"

[[trusted.memchr]]
criteria = "safe-to-run"
user-id = 189 # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2026-02-12"

[[trusted.new_debug_unreachable]]
criteria = "safe-to-run"
user-id = 2017 # Matt Brubeck (mbrubeck)
start = "2019-02-26"
end = "2026-04-10"

[[trusted.pango]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2020-08-11"
end = "2026-02-12"

[[trusted.pango-sys]]
criteria = "safe-to-run"
user-id = 3623 # Sebastian Dröge (sdroege)
start = "2022-01-15"
end = "2026-02-12"

[[trusted.parking_lot]]
criteria = "safe-to-run"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2026-04-10"

[[trusted.parking_lot_core]]
criteria = "safe-to-run"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2026-04-10"

[[trusted.phf]]
criteria = "safe-to-run"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2021-06-17"
end = "2026-04-10"

[[trusted.phf_codegen]]
criteria = "safe-to-run"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2021-06-17"
end = "2026-04-10"

[[trusted.phf_generator]]
criteria = "safe-to-run"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2021-06-17"
end = "2026-04-10"

[[trusted.phf_macros]]
criteria = "safe-to-run"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2021-06-17"
end = "2026-04-10"

[[trusted.phf_shared]]
criteria = "safe-to-run"
user-id = 51017 # Yuki Okushi (JohnTitor)
start = "2021-06-17"
end = "2026-04-10"

[[trusted.portable-atomic]]
criteria = "safe-to-run"
user-id = 33035 # Taiki Endo (taiki-e)
start = "2022-02-24"
end = "2026-05-16"

[[trusted.portable-atomic-util]]
criteria = "safe-to-run"
user-id = 33035 # Taiki Endo (taiki-e)
start = "2023-01-15"
end = "2026-05-16"

[[trusted.scopeguard]]
criteria = "safe-to-run"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2020-02-16"
end = "2026-04-10"

[[trusted.serde_spanned]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2023-01-20"
end = "2026-02-12"

[[trusted.slab]]
criteria = "safe-to-run"
user-id = 6741 # Alice Ryhl (Darksonn)
start = "2021-10-13"
end = "2026-02-12"

[[trusted.soup3]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2022-10-10"
end = "2026-02-22"

[[trusted.soup3-sys]]
criteria = "safe-to-run"
user-id = 54339 # Bilal Elmoussaoui (bilelmoussaoui)
start = "2022-10-10"
end = "2026-02-22"

[[trusted.string_cache]]
criteria = "safe-to-run"
user-id = 2396 # Josh Matthews (jdm)
start = "2021-10-12"
end = "2026-04-10"
notes = "Respectable whatwg & servo person"

[[trusted.string_cache_codegen]]
criteria = "safe-to-run"
user-id = 2396 # Josh Matthews (jdm)
start = "2022-03-27"
end = "2026-04-10"
notes = "Respectable whatwg & servo person"

[[trusted.syn]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-02-12"

[[trusted.target-lexicon]]
criteria = "safe-to-run"
user-id = 696 # Nick Fitzgerald (fitzgen)
start = "2024-07-30"
end = "2026-02-12"

[[trusted.tendril]]
criteria = "safe-to-run"
user-id = 2396 # Josh Matthews (jdm)
start = "2022-03-27"
end = "2026-04-10"
notes = "Respectable whatwg & servo person"

[[trusted.toml]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2022-12-14"
end = "2026-02-12"

[[trusted.toml_edit]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2021-09-13"
end = "2026-02-12"

[[trusted.windows-sys]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2026-05-16"

[[trusted.windows-targets]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2026-05-16"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2026-05-16"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2026-05-16"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2026-05-16"

[[trusted.windows_i686_gnullvm]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2024-04-02"
end = "2026-05-16"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2026-05-16"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2026-05-16"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2026-05-16"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-run"
user-id = 64539 # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2026-05-16"

[[trusted.winnow]]
criteria = "safe-to-run"
user-id = 6743 # Ed Page (epage)
start = "2023-02-22"
end = "2026-02-12"
