
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.gnome-releng]
url = "https://gitlab.gnome.org/Teams/Releng/rust-supply-chain/-/raw/main/gnome-audited/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.swsnr]
url = "https://codeberg.org/swsnr/rust-supply-chain/raw/branch/main/audits.toml"

[policy.pictureoftheday]
criteria = "safe-to-run"

[[exemptions.redox_syscall]]
version = "0.5.12"
criteria = "safe-to-run"

[[exemptions.toml_parser]]
version = "1.0.4"
criteria = "safe-to-run"
