name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    # Run this workflow also when a PR becomes ready for review; this enables us
    # to open automated PRs as draft, and then explicitly make them ready for
    # review manually to trigger the workflow.
    types: [opened, reopened, synchronize, ready_for_review]

env:
  CARGO_TERM_COLOR: always

jobs:
  # See https://mozilla.github.io/cargo-vet/configuring-ci.html
  cargo-vet:
    name: Vet Dependencies
    runs-on: ubuntu-latest
    env:
      CARGO_VET_VERSION: 0.10.0
      # Only consider Linux dependencies, as that's all I care for.
      # Seems to be unofficial, see https://github.com/mozilla/cargo-vet/issues/579, but works
      CARGO_BUILD_TARGET: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@master
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/cargo-vet
          key: cargo-vet-bin-${{ env.CARGO_VET_VERSION }}
      - run: echo "${{ runner.tool_cache }}/cargo-vet/bin" >> $GITHUB_PATH
      - run: cargo install --root ${{ runner.tool_cache }}/cargo-vet --version ${{ env.CARGO_VET_VERSION }} cargo-vet
      - run: cargo vet --locked

  build:
    name: Build & lint
    runs-on: ubuntu-latest
    container:
      # For Gtk support
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
        with:
          components: rustfmt, clippy
      # See https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-rust-${{ steps.toolchain.outputs.cachekey }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo fmt --check
      - run: cargo build
      - run: cargo clippy --all-targets
      - run: cargo test
      - name: cargo deny check
        uses: EmbarkStudios/cargo-deny-action@v2
